### Login
post http://cursonodejs17-prod.us-east-1.elasticbeanstalk.com/auth/v1/login
Content-Type: application/json

{
    "email": "sergio@email.com",
    "password": "ElG1ganteD3lFindelMund0"
}

### new access token
post http://localhost:3000/auth/v1/new-access-token
Content-Type: application/json

{
    "refreshToken": "493c7654-bcab-4f1c-a480-0c50a49a6207"
}

### Register
#post http://localhost:3000/auth/v1/register
post http://cursonodejs17-prod.us-east-1.elasticbeanstalk.com/auth/v1/register
Content-Type: application/json

{
    "name": "Sergio",
    "lastname": "Hidalgo",
    "email": "sergio@email.com",
    "password": "ElG1ganteD3lFindelMund0",
    "roles": [{"roleId": "d538843b-95d1-406c-a062-c6f5f97da154"}]
}

### Enable 2FA
post http://cursonodejs17-prod.us-east-1.elasticbeanstalk.com/auth/v1/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZDc5MzJhYy00NWU4LTRmNTgtYjYxNC1mNjAxMTY4ZDFlMTkiLCJuYW1lIjoiU2VyZ2lvIiwibGFzdG5hbWUiOiJIaWRhbGdvIiwicm9sZXMiOlt7InJvbGVJZCI6ImQ1Mzg4NDNiLTk1ZDEtNDA2Yy1hMDYyLWM2ZjVmOTdkYTE1NCIsInJvbGVOYW1lIjoiQURNSU4ifV0sImVuYWJsZTJGQSI6ZmFsc2UsImlhdCI6MTcxODQ3Njk1OSwiZXhwIjoxNzE4NDk0OTU5fQ.02lPDaj58c88mcspFE_TOpMfGIiY2dVuC7HU6o5OHVY

{
    "secret": "O4SF4WTUOI5XOSJSJJTFAU2MJJICYTK2OVNDSL2LKY7FU52EPFEQ",
    "token": "810566"
}


### Verify 2FA
post http://cursonodejs17-prod.us-east-1.elasticbeanstalk.com/auth/v1/verify-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5ZDc5MzJhYy00NWU4LTRmNTgtYjYxNC1mNjAxMTY4ZDFlMTkiLCJuYW1lIjoiU2VyZ2lvIiwibGFzdG5hbWUiOiJIaWRhbGdvIiwicm9sZXMiOlt7InJvbGVJZCI6ImQ1Mzg4NDNiLTk1ZDEtNDA2Yy1hMDYyLWM2ZjVmOTdkYTE1NCIsInJvbGVOYW1lIjoiQURNSU4ifV0sImVuYWJsZTJGQSI6ZmFsc2UsImlhdCI6MTcxODQ3NzExNiwiZXhwIjoxNzE4NDk1MTE2fQ.c0K9dCsJlHuZuiuoTJ-uTpHsi_wAl77lKL04ppEq8Vw

{
    "token": "718813"
}
