### Login
post http://localhost:3000/auth/v1/login
Content-Type: application/json

{
    "email": "antonio8.cardenas@email.com",
    "password": "123456789"
}

### new access token
post http://localhost:3000/auth/v1/new-access-token
Content-Type: application/json

{
    "refreshToken": "493c7654-bcab-4f1c-a480-0c50a49a6207"
}

### Register
post http://localhost:3000/auth/v1/register
Content-Type: application/json

{
    "name": "An",
    "lastname": "Cá",
    "email": "antonio8.cardenas@email.com",
    "password": "12345678",
    "roles": [{"roleId": "d538843b-95d1-406c-a062-c6f5f97da154"}]
}

### Enable 2FA
post http://localhost:3000/auth/v1/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YzYyMzAwMi1kMWVlLTQzOWEtYWYxNC1iM2NkYmVkZmYzNDUiLCJuYW1lIjoiQW50b25pbzgiLCJsYXN0bmFtZSI6IkPDoXJkZW5hcyIsInJvbGVzIjpbeyJyb2xlSWQiOiIwOTI3MWJmZi1kZWYyLTQ5MmUtOThiYi04ZjUzM2M3NGFhYzQiLCJyb2xlTmFtZSI6Ik9QRVJBVE9SIn0seyJyb2xlSWQiOiJkNTM4ODQzYi05NWQxLTQwNmMtYTA2Mi1jNmY1Zjk3ZGExNTQiLCJyb2xlTmFtZSI6IkFETUlOIn1dLCJlbmFibGUyRkEiOmZhbHNlLCJpYXQiOjE3MTc4NTQ3MzIsImV4cCI6MTcxNzg1NjUzMn0.j4Cp1WHqC7Vq900A8OmAagRPbxcATv7uH3fX2F3cBho

{
    "secret": "K46HQ5TXIZYDK5LFLZBCGQZRNFUHO6LOLZOTSPDYKFTSGJKNFZHQ",
    "token": "067241"
}


### Verify 2FA
post http://localhost:3000/auth/v1/verify-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YzYyMzAwMi1kMWVlLTQzOWEtYWYxNC1iM2NkYmVkZmYzNDUiLCJuYW1lIjoiQW50b25pbzgiLCJsYXN0bmFtZSI6IkPDoXJkZW5hcyIsInJvbGVzIjpbeyJyb2xlSWQiOiIwOTI3MWJmZi1kZWYyLTQ5MmUtOThiYi04ZjUzM2M3NGFhYzQiLCJyb2xlTmFtZSI6Ik9QRVJBVE9SIn0seyJyb2xlSWQiOiJkNTM4ODQzYi05NWQxLTQwNmMtYTA2Mi1jNmY1Zjk3ZGExNTQiLCJyb2xlTmFtZSI6IkFETUlOIn1dLCJlbmFibGUyRkEiOmZhbHNlLCJpYXQiOjE3MTc4NTUwMzQsImV4cCI6MTcxNzg3MzAzNH0.fejpm6g4pzP3B6DlPgRlZYk7odo5K0HSsyems5K90mI

{
    "token": "742300"
}
