### Login
post http://localhost:3000/auth/v1/login
Content-Type: application/json

{
    "email": "sergio@email.com",
    "password": "ElG1ganteD3lFindelMund0"
}

### new access token
post http://localhost:3000/auth/v1/new-access-token
Content-Type: application/json

{
    "refreshToken": "493c7654-bcab-4f1c-a480-0c50a49a6207"
}

### Register
post http://localhost:3000/auth/v1/register
Content-Type: application/json

{
    "name": "Sergio",
    "lastname": "Hidalgo",
    "email": "sergio@email.com",
    "password": "ElG1ganteD3lFindelMund0",
    "roles": [{"roleId": "d538843b-95d1-406c-a062-c6f5f97da154"}]
}

### Enable 2FA
post http://localhost:3000/auth/v1/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlOTc1YjQwNy05Y2FjLTQwZDQtODIzOC1hZDQyMDc1OTYzOGMiLCJuYW1lIjoiU2VyZ2lvIiwibGFzdG5hbWUiOiJIaWRhbGdvIiwicm9sZXMiOlt7InJvbGVJZCI6ImQ1Mzg4NDNiLTk1ZDEtNDA2Yy1hMDYyLWM2ZjVmOTdkYTE1NCIsInJvbGVOYW1lIjoiQURNSU4ifV0sImVuYWJsZTJGQSI6ZmFsc2UsImlhdCI6MTcxODQ2NDA2MSwiZXhwIjoxNzE4NDgyMDYxfQ.ZS9i9rn0fhhoMKBa1kbsK0gyexM8XvOqd0ELZ7Qx1OQ

{
    "secret": "I4XGEIJZJRAS6MCKKFKHUOSIHJ2TCPBEMRFFEUKFLJIGS6ZDGFIA",
    "token": "224904"
}


### Verify 2FA
post http://localhost:3000/auth/v1/verify-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlOTc1YjQwNy05Y2FjLTQwZDQtODIzOC1hZDQyMDc1OTYzOGMiLCJuYW1lIjoiU2VyZ2lvIiwibGFzdG5hbWUiOiJIaWRhbGdvIiwicm9sZXMiOlt7InJvbGVJZCI6ImQ1Mzg4NDNiLTk1ZDEtNDA2Yy1hMDYyLWM2ZjVmOTdkYTE1NCIsInJvbGVOYW1lIjoiQURNSU4ifV0sImVuYWJsZTJGQSI6ZmFsc2UsImlhdCI6MTcxODQ2NDYwOCwiZXhwIjoxNzE4NDgyNjA4fQ.mjOEXxE4D3t1IyqmS5aMOEWm-5OFe0Say0NtQF9rmoA

{
    "token": "507569"
}
