### 
get http://localhost:3000/

###
get http://localhost:3000/student

###
get http://localhost:3000/student/5


###
get http://localhost:3000/student/page?page=4&limit=2

###
post http://localhost:3000/student
Content-Type: application/json

{
    "name": "Juan",
    "lastname": "Perez",
    "age": 20,
    "email": "juan.perez@email.com",
    "phone": "1234567890",
    "address": "Calle 123",
    "city": "Bogota",
    "country": "Colombia",
    "gender": "male",
    "career": "Ingeniería de sistemas",
    "semester": 5,
    "createdAt": "2024-05-04T16:38:00.000Z"
}

###
delete http://localhost:3000/student/5


###
get http://localhost:3000/student/5

###
put http://localhost:3000/student/5
Content-Type: application/json

{
    "name": "Juan"
}

