### Create a new user
post http://localhost:3000/user/v1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YzYyMzAwMi1kMWVlLTQzOWEtYWYxNC1iM2NkYmVkZmYzNDUiLCJuYW1lIjoiQW50b25pbzgiLCJsYXN0bmFtZSI6IkPDoXJkZW5hcyIsInJvbGVzIjpbeyJyb2xlSWQiOiIwOTI3MWJmZi1kZWYyLTQ5MmUtOThiYi04ZjUzM2M3NGFhYzQiLCJyb2xlTmFtZSI6Ik9QRVJBVE9SIn0seyJyb2xlSWQiOiJkNTM4ODQzYi05NWQxLTQwNmMtYTA2Mi1jNmY1Zjk3ZGExNTQiLCJyb2xlTmFtZSI6IkFETUlOIn1dLCJlbmFibGUyRkEiOnRydWUsImlhdCI6MTcxNzg1NTA2NSwiZXhwIjoxNzE3ODczMDY1fQ.eLvOD08kNtE6WjjoO8lDxBzNJK1Ler9mquDJrO7FW3w

{
    "name": "Antonio3",
    "lastname": "Cárdenas",
    "email": "antoniocardenas@email.com",
    "password": "12345",
    "roles": [{"roleId": "d538843b-95d1-406c-a062-c6f5f97da154"}, {"roleId": "09271bff-def2-492e-98bb-8f533c74aac4"}]
}

### List all users
get http://localhost:3000/user/v1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlOTc1YjQwNy05Y2FjLTQwZDQtODIzOC1hZDQyMDc1OTYzOGMiLCJuYW1lIjoiU2VyZ2lvIiwibGFzdG5hbWUiOiJIaWRhbGdvIiwicm9sZXMiOlt7InJvbGVJZCI6ImQ1Mzg4NDNiLTk1ZDEtNDA2Yy1hMDYyLWM2ZjVmOTdkYTE1NCIsInJvbGVOYW1lIjoiQURNSU4ifV0sImVuYWJsZTJGQSI6dHJ1ZSwiaWF0IjoxNzE4NDY0NjI5LCJleHAiOjE3MTg0ODI2Mjl9.H0Md2ZzkYXZd3cl3geWY6iLj30PX4tBRVgc40tyIOpM

### Get user by id
get http://localhost:3000/user/v1/9b4278d9-f53a-4d3b-bdcf-8c9c93d659d8

### Update user
put http://localhost:3000/user/v1/b9666e21-76b2-443c-9140-4968cd677ece
Content-Type: application/json

{
    "name": "Jana",
    "lastname": "Pastizales"
}

### Get users by page
get http://localhost:3000/user/v1/page?page=0&limit=10

### Delete user
delete http://localhost:3000/user/v1/b9666e21-76b2-443c-9140-4968cd677ece
